### ISSUE TITLE
Submit method throws an error

### ISSUE THREAD

**Issue by BlackDrakex** [laravel/precognition#101]
### Laravel Precognition Plugin Version

0.5.10

### Laravel Version

11.7.0

### Plugin

Vue w/ Inertia

### Description

The type of submit method on form returned by useForm suggests that i can be called with either one, two, or three arguments. Either just config as the first parameter, or request method plus url, or request method plus url plus options. If you try to call it with just two arguments, it throws an errror when request fails `Cannot read properties of undefined (reading 'onError')` because `submitOptions` is undefined when code checks for `submitOptions.onError` in if statement. This doesn't actually break anything as far as i know, but would be nice to add nullsafe operator there.

### Steps To Reproduce

Simply create a new form and try to submit it specifying both request method and url.
```
const form = useForm('method', 'url', { field: null });
form.submit('anotherMethod', 'anotherUrl');
```
If request fails and onError executed, you'll see an error.

**Comment by timacdonald** [comment]
Thanks for reporting this one.

I've opened a PR to fix this: https://github.com/laravel/precognition/pull/102
