### ISSUE TITLE
Inertia: get redirect 302 instead of 422 when submit form

### ISSUE THREAD

**Issue by et-hoangdv** [laravel/precognition#106]
### Laravel Precognition Plugin Version

0.5.12

### Laravel Version

11.9

### Description

I'm using precognition with inertia. `laravel-precognition-vue-inertia` and get status 302 when submit form instead of 422 which I excepted.

### Steps To Reproduce

2 steps.

1. I input the wrong data to an input and then it call API -> get status 422 as excepted. `work`

2. I submit the form with the same data that got 422 at step 1 -> This time I got status 302.

The different I notice between both API is
step 1 have: `precognition: true` not step 2 don't.
step 2 got `x-inertia: true` and `x-requested-with: XMLHttpRequest` and step 1 don't.

**Comment by timacdonald** [comment]
Hi, @et-hoangdv, this seems to be expected behaviour to me.

Inertia will not return 422 responses. It converts them to 302 Found responses.

What is the particular issue you are facing while using Precognition?

**Comment by timacdonald** [comment]
I'm going to close this issue due to inactivity.

We can certainly re-open the issue if you can provide the information requested.

Hope you were able to find a solution to the issue.
