### ISSUE TITLE
Migration Issues: Upgrading from Inertia.js v1 to v2

### ISSUE THREAD

**Issue by jrmybtlr** [laravel/precognition#107]
### Laravel Precognition Plugin Version

"laravel-precognition-react-inertia": "^0.5.6",

### Laravel Version

11.9

### Plugin

React w/ Inertia

## Description
During the migration from Inertia.js v1 to v2, we're encountering peer dependency conflicts with `laravel-precognition-react-inertia` which is still expecting Inertia.js v1.

## Current Behavior
- Attempting to upgrade to `@inertiajs/react@2.x`
- `laravel-precognition-react-inertia@0.5.13` is locked to `@inertiajs/react@^1.0.0`
- NPM throws dependency resolution warnings

## Error Message
```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: n*******h.laravel.com@undefined
npm warn Found: @inertiajs/react@1.2.0
npm warn node_modules/@inertiajs/react
npm warn   peer @inertiajs/react@"^1.0.0" from laravel-precognition-react-inertia@0.5.13
npm warn   node_modules/laravel-precognition-react-inertia
npm warn     laravel-precognition-react-inertia@"^0.5.6" from the root project
```

### Steps To Reproduce

1. Start with a working Inertia.js v1 installation
2. Run upgrade command:
   ```bash
   npm install @inertiajs/react@next
   ```

**Comment by onlime** [comment]
Tested the Vue version with Inertia.js v2 `@inertiajs/vue3@2.0.0-beta.2` by force installing (`npm i --force`) `laravel-precognition-vue-inertia@0.5.13` which works perfectly fine. So, please just bump the peer deps. Thanks @timacdonald !

**Comment by timacdonald** [comment]
Hey, folks, will be doing some testing across the stacks next week. Can't imagine there is anything breaking.

Will tagged a new version once we confirm all the stacks.

**Comment by valh1996** [comment]
> Hey, folks, will be doing some testing across the stacks next week. Can't imagine there is anything breaking.

Thank you! Do you have any news on this subject please ?

**Comment by timacdonald** [comment]
I've opened a PR to add inertia 2.0 support: https://github.com/laravel/precognition/pull/108

We can close this PR and follow the PR progress.
