### ISSUE TITLE
Arrays being sent as empty when using "laravel-precognition-react-inertia"

### ISSUE THREAD

**Issue by tommica** [laravel/precognition#11]
### Laravel Precognition Plugin Version

0.2.2

### Laravel Version

10.13.0

### Plugin

React

### Description

For some reason, when sending a "precognition" request, the arrays are empty - in this case I have this type definition:
`demo?: {items: string[]};` and the data is set to `demo: {items: ["foo", "bar"]},` and when the form is submitted to the backend to be created, the data is correct - but when doing a precognition validation, the arrays are empty.

Please see the screenshot. The console.log statement is triggered just before the calling `form.validation(...)` method.

Initially I thought it was because I was calling the validation on a different field, but I can see that rest of the form data is sent along, but all arrays are just truncated.

![Screenshot 2023-06-05 at 10 57 25](https://github.com/laravel/precognition/assets/1391027/96375459-5ff8-4cbe-90e8-afdd87c573f6)

### Steps To Reproduce

```
const initialValues = {
        email: "foo@test.test",
        demo: ["foo", "bar"],
};

const actionRoute = "/store";
const form = useForm('post', actionRoute, initialValues);

function submit(e: FormEvent) {
      e.preventDefault();
      console.log(form.data);
      form.post(actionRoute);
}

return (
<form method='POST' action={actionRoute} onSubmit={submit}>
<input
      type='email'
      value={form.data.email}
      onChange={e => form.setData('email', e.target.value)}
      onBlur={() => {console.log(form.data); return form.validate('email')}}
  />

<button type='submit'>YOLO</button>
</form>
)

```

**Comment by timacdonald** [comment]
Thanks for raising this issue. I've opened a PR to address the problem. I'll close this and we can track the issue in the PR: https://github.com/laravel/precognition/pull/15
