### ISSUE TITLE
processing value always returns false

### ISSUE THREAD

**Issue by jptagorda** [laravel/precognition#12]
### Laravel Precognition Plugin Version

0.2.2

### Laravel Version

10.10

### Plugin

React

### Description

After implementing precognition on freshly installed laravel + breeze react from default register.jsx file the form.processing value always returns false when the form was submitted and changed the chrome network settings to Slow 3g throttling.

### Steps To Reproduce

  import { useEffect } from 'react';
  import GuestLayout from '@/Layouts/GuestLayout';
  import InputError from '@/Components/InputError';
  import InputLabel from '@/Components/InputLabel';
  import PrimaryButton from '@/Components/PrimaryButton';
  import TextInput from '@/Components/TextInput';
  import { Head, Link } from '@inertiajs/react';
  import {useForm} from 'laravel-precognition-react-inertia'

export default function Register() {
    const form = useForm('post', route('register'),{
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
    });

    useEffect(() => {
        return () => {
            form.reset('password', 'password_confirmation');
        };
    }, []);

    const submit = (e) => {
        e.preventDefault();

        form.submit();
    };

    return (
        <GuestLayout>
            <Head title="Register" />

            <form onSubmit={submit}>
                <div>
                    <InputLabel htmlFor="name" value="Name" />

                    <TextInput
                        id="name"
                        name="name"
                        value={form.data.name}
                        className="mt-1 block w-full"
                        autoComplete="name"
                        isFocused={true}
                        onChange={(e) => form.setData('name', e.target.value)}
                        required
                    />

                    <InputError message={form.errors.name} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="email" value="Email" />

                    <TextInput
                        id="email"
                        type="email"
                        name="email"
                        value={form.data.email}
                        className="mt-1 block w-full"
                        autoComplete="username"
                        onChange={(e) => form.setData('email', e.target.value)}
                        required
                    />

                    <InputError message={form.errors.email} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password" value="Password" />

                    <TextInput
                        id="password"
                        type="password"
                        name="password"
                        value={form.data.password}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        onChange={(e) => form.setData('password', e.target.value)}
                        required
                    />

                    <InputError message={form.errors.password} className="mt-2" />
                </div>

                <div className="mt-4">
                    <InputLabel htmlFor="password_confirmation" value="Confirm Password" />

                    <TextInput
                        id="password_confirmation"
                        type="password"
                        name="password_confirmation"
                        value={form.data.password_confirmation}
                        className="mt-1 block w-full"
                        autoComplete="new-password"
                        onChange={(e) => form.setData('password_confirmation', e.target.value)}
                        required
                    />

                    <InputError message={form.errors.password_confirmation} className="mt-2" />
                </div>

                <div className="flex items-center justify-end mt-4">
                    <Link
                        href={route('login')}
                        className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Already registered?
                    </Link>
                    <PrimaryButton className="ml-4" disabled={form.processing}>
                        Register
                    </PrimaryButton>
                </div>
                    <p>{`${form.processing}`}</p>
            </form>
        </GuestLayout>
    );
}

**Comment by JSellis** [comment]
I've noticed this too. When using the default Inertia useForm hook, `form.processing` works as expected but when using the augmented hook from `laravel-precognition-react-inertia`, `form.processing` always returns false.

**Comment by jptagorda** [comment]
i just want to disable the submit button when submitting the form then i found this problem

**Comment by timacdonald** [comment]
Hey folks, sorry you ran into this issue. I've created a fix and we can follow the issue in the PR https://github.com/laravel/precognition/pull/13

**Comment by jptagorda** [comment]
works perfectly! thanks!

**Comment by timacdonald** [comment]
Excellent!
