### ISSUE TITLE
Add TypeScript Return Types for useForm

### ISSUE THREAD

**Issue by pixelmund** [laravel/precognition#16]
Currently the Inertia `useForm` for React and Vue has a return type of `any`, it would be awesome to have it typed.

EDIT: Actually when testing on my fork, we can probably get rid of the implicit `any` return and let typescript infer the type correctly, but it's giving me an weird error on the vue-inertia package. So probably better to type it!

**Comment by timacdonald** [comment]
We will likely improve this soon. Going to close, however, as it isn't a functional bug.

**Comment by joelstein** [comment]
See https://github.com/laravel/precognition/pull/110.
