### ISSUE TITLE
Allow for forced validation of fields

### ISSUE THREAD

**Issue by 3rgo** [laravel/precognition#17]
Hello,

I'm using the laravel-precognition-react frontend library, and on my form I want to allow the user to autocomplete fields. When using Chrome, it will allow for multiple fields to be auto completed at once.
My case is in my multi-step Registration form : in the first step it will fill first name, last name, email and phone.

I've spend the past 2 hours trying to build something that would allow for the autocompleted fields to be validated before moving on to the next step, nothing seems to work properly and feel robust enough to deploy it to users.

Would it be possible to pass a boolean 2nd parameter to the validate function, or expose a separate "forceValidation" method ?

**Comment by timacdonald** [comment]
@3rgo I can see this seems to be an issue due to the way React works. Doesn't seem to impact Vue, for example.

If we were to add such function, could you eloborate on where and when you would call it?

How would you know to invoke the new "forceValidation" method?

**Comment by 3rgo** [comment]
Hi @timacdonald ! Thanks for the followup !

At the moment my situation is the following (in a Registration form) :

1. User fills multiple form fields at once, either with browser autofill or an extension (or by any other means that fills multiple fields at once)
2. All the fields trigger the onChange event, updating the state with the latest value
3. The focused field will be validated on blur (for example when the submit button is clicked)
4. Any other field that was not focused and blurred manually will not be validated using precognition
5. If the form's final submission returns errors, the user may be taken back a few steps

My idea is that the validation can be triggered manually to improve the user experience.
This way, no front-end validation would be required, since we let Laravel do it the way it would be done when the request would be sent (which is the point of the library after all 😄 ).

If I execute the following code when clicking the next button, no validation request is sent (and no idea why) :
```js
fields.forEach((f) => {
    form.validate(f);
});
```
My current strategy is to perform validation when onChange is triggered (using a debounced call), which may do much more queries than necessary if each input is filled manually. 

In my case it is a multi-step form, and I want to use precognition to ensure data is valid before going to the next step, i.e. when the user clicks the "next" button :

1. Precognitive validation request is sent (with all fields if possible)
2. Until the response is received, a loader is displayed
3. When response is received, either the errors are displayed or the form advances to the next step

I hope I'm being clear enough, let me know if I need to rephrase some (or all 😅 ) of it

**Comment by timacdonald** [comment]
@3rgo unfortunately I'm about to take some leave. I will come back to this issue, if it isn't resolved, when I get back.

I have a feeling this may already be possible with configuration, but I will need to setup a project and have a play.

**Comment by timacdonald** [comment]
I take it back. I've opened a PR that should address this issue. See #26.

**Comment by 3rgo** [comment]
Thank you for the PR, and enjoy your holiday !
