### ISSUE TITLE
Fields appear as valid before they are set to invalid

### ISSUE THREAD

**Issue by 3rgo** [laravel/precognition#18]
### Laravel Precognition Plugin Version

0.3.2

### Laravel Version

10.10

### Plugin

React

### Description

When displaying both "valid" and "invalid" status on a field (for example with an icon), and sending a precognitive request with an invalid value, the field will appear as valid before appearing as invalid

### Steps To Reproduce

Minimal code can be found on the following public repository : https://github.com/3rgo/demo-laravel-precognitive

Just input an invalid email, either with incorrect format or with an existing value in the database (seeders present and values are displayed on the right side of the page) then switch fields to trigger the validation.

**Comment by timacdonald** [comment]
I've opened #19 to address this issue. I'll close this and we can follow the PR instead.
