### ISSUE TITLE
allow useForm method and url to be "reactive"

### ISSUE THREAD

**Issue by makroxyz** [laravel/precognition#20]
Hi. I have a vue component (Modal dialog)  that can post or patch a record

```
props: {
  item: Object
}

const form = useForm(method, url, {...})
```

route and method should change if item is going to be created or updated (for example just check if ID is null)

with inertiajs form I simply set method and route while submitting... but precognition is not reactive...

Is there a workaround? Am I missing something?

**Comment by timacdonald** [comment]
Can you provide a full example of how you currently do this?

**Comment by makroxyz** [comment]
I have a modal dialog for create/update person records.
This is a simple example using inertiajs form

Modal.vue
```
<template>
<div class="modal" v-if="modelValue">
    <input v-model="form.first_name" />
    <input v-model="form.last_name" />
    <!--- other n fields ... --->

    <button @click="submit">OK</button>
</div>
</template>

<script setup>
import {useForm} from 'inertiajs/vue3'
import {computed} from 'vue'

const props = defineProps = ({
   modelValue: Boolean,
   person: Object
})

const emit = defineEmits(['update:modelValue'])

const form = useForm({
  first_name: props.first_name,
  last_name: props.last_name,
 //....
})

const exists = computed(() => props.person?.id !== null)

const submit = () => {
  let method, url

  if (exists) {
    method = 'patch'
    url = '/people/' + person.id
  } else {
    method = 'post'
    url = '/people'
  }

  form[method](url, {
      onSuccess: () => emit('update:modelValue', false)
  })
}
</script>
```

in precognition ```useForm``` composable ```method``` and ```url``` are strings and cannot change their  values after form object declaration.
Maybe is possible to re-declare entire object when person property changes but I think it isn't a good way

**Comment by timacdonald** [comment]
I've opened #20 which allows you to pass a callback as the method / url.

```vue
<script setup>
import {useForm} from 'laravel-precognition-vue'
import {computed} from 'vue'

const props = defineProps = ({
    modelValue: Boolean,
    person: Object
})

const exists = computed(() => props.person?.id !== null)

const form = useForm(
    () => exists.value ? 'patch' : 'post',
    () => exists.value ? `/people/${person.id}` : '/people',
    {
        first_name: props.first_name,
        last_name: props.last_name,
        // ...
    }
)

const submit = () => {
    form.submit({
        onSuccess: /* ... */,
    })
}
</script>
```

I'll close this and we can follow the PR.

**Comment by timacdonald** [comment]
Usually do releases on a Tuesday.

**Comment by makroxyz** [comment]
> Usually do releases on a Tuesday.

Sorry for writing again... but any news about release?
