### ISSUE TITLE
Allow for uncontrolled form inputs in React's useForm

### ISSUE THREAD

**Issue by weavdale** [laravel/precognition#23]
The Precognintion documentation page recommends using controlled inputs with `useForm`. 
```js
import { useForm } from 'laravel-precognition-react';
 
export default function Form() {
    const form = useForm('post', '/users', {
        name: '',
        email: '',
    });
 
    const submit = (e) => {
        e.preventDefault();
 
        form.submit();
    };
 
    return (
        <form onSubmit={submit}>
            <label for="name">Name</label>
            <input
                id="name"
                value={form.data.name}
                onChange={(e) => form.setData('name', e.target.value)}
                onBlur={() => form.validate('name')}
            />
            {form.invalid('name') && <div>{form.errors.name}</div>}
 
            <label for="email">Email</label>
            <input
                id="email"
                value={form.data.email}
                onChange={(e) => form.setData('email', e.target.value)}
                onBlur={() => form.validate('email')}
            />
            {form.invalid('email') && <div>{form.errors.email}</div>}
 
            <button>Create User</button>
        </form>
    );
};
```

`useForm` state is manage with React's `useState` hook, so every character typed in a form field causes a re-render. This is fine for smaller forms. However, I have a large grid like forms with hundred's of form inputs. There is substantial lag when typing in a form field which make the form unusable. This is a result of React constantly re-rendering on every key stroke with "controlled inputs". When testing with Vue and Svelte I didn't have this problem because they do state management and re-rending differently.

Kent C Dodds recommends using "uncontrolled inputs" to speed up React form performance (https://epicreact.dev/improve-the-performance-of-your-react-forms/). Basically you hook into the HTML form's native submit event and grab the field values from it instead of having an `onChange` handler for each form field.

However, this approach is a little difficult to use with `useForm` currently. If I initialize `useForm` with no data, then have a `submit` event handler to set `useForm`'s data from the HTML form submit event, I can't immediately submit the form with precognition. This is because React batches state updates and `useForm`'s data won't be available till next re-render.
```js
import { useForm } from 'laravel-precognition-react';
 
export default function Form() {
    const form = useForm('post', '/users', {});
 
    const submit = (e) => {
        e.preventDefault();
        const formData = new FormData(e.currentTarget);
        const fieldValues = Object.fromEntries(formData.entries());
        form.setData(fieldValues);
        form.submit(); // form.data is not available till next render so won't submit
    };
 
    return (
        <form onSubmit={submit}>
            <label for="name">Name</label>
            <input
                id="name"
                name="name"
            />
 
            <label for="email">Email</label>
            <input
                id="email" 
                name="email"
            />
 
            <button type="submit">Create User</button>
        </form>
    );
};
```

Is there a way we can enhance `useForm` to allow use of either "controlled inputs" or "uncontrolled inputs"? I believe this is also a problem in Inertia's `userForm`.

**Comment by timacdonald** [comment]
@weavdale regarding controlling the data manually, you should be able to do something like this (untested):

```js
import { useForm } from 'laravel-precognition-react';
import { useState } from 'react';
 
export default function Form() {
    const form = useForm('post', '/users', {});

    const submit = (e) => {
        e.preventDefault();

        form.submit({
            data: Object.fromEntries((new FormData(e.currentTarget)).entries()),
        })
    };
 
    return (
        <form onSubmit={submit}>
            <label for="name">Name</label>
            <input
                id="name"
                name="name"
            />
 
            <label for="email">Email</label>
            <input
                id="email" 
                name="email"
            />
 
            <button 
                type="submit"
                disabled={form.processing}
            >
                 Create User
            </button>
        </form>
    );
};
```

**Comment by timacdonald** [comment]
Actually, you will need to wait until we tagged this PR in a release: https://github.com/laravel/precognition/pull/24

Then the above approach should work for you.

**Comment by weavdale** [comment]
Awesome! Thanks for the help!
