### ISSUE TITLE
Function to return bool if form has any fields touched

### ISSUE THREAD

**Issue by MarekVikartovsky** [laravel/precognition#27]
Hello,

I would like to ask you for a function, which would return a boolean, if form has any fields touched.

Thank you.

**Comment by driesvints** [comment]
We currently have no plans for this ourselves sorry.

**Comment by timacdonald** [comment]
@MarekVikartovsky what is the use case for this?

**Comment by MarekVikartovsky** [comment]
Hi @timacdonald 

Imagine, you have "one big form with one submit button", and this big form is split into multiple subforms, because you do not want to send one big POST/PUT request. Every subform is precognitive form instance, but submitting is not done via precognitive form instance, because of some custom logic. So when you press the submit button, event is emitted, subforms will catch this event and do the submit.
But if subform does not have any changes, you do not want to send request to backend. So there will be handy to have a function on precognitive form, which returns  information, if any change was made.
