### ISSUE TITLE
Laravel Precognition returns wrong values for valid and invalid when field is not yet touched

### ISSUE THREAD

**Issue by Sagmedjo** [laravel/precognition#29]
### Laravel Precognition Plugin Version

0.3.2

### Laravel Version

10.14.1

### Plugin

Vue w/ Inertia

### Description

When checking for the validity of a untouched field, the methods "valid" and "invalid" both return false. The issue with this behaviour is that nullable fields are wrongly classified as invalid when using the "valid" method and required fields are wrongly classified as valid when using the "invalid" method.

I think a initial request to check for required fields would be helpful, so that the "valid" and "invalid" methods can be used before the user has even interacted with the form.

### Steps To Reproduce

You can see the issue in this repository: "[https://github.com/Sagmedjo/precognitionIssue](https://github.com/Sagmedjo/precognitionIssue)". When submitting the form look into the DevTools Console

**Comment by jessarcher** [comment]
Thanks for reporting this and providing a repository @Sagmedjo!

As this involves a potential behaviour change, I'd like to discuss this with @timacdonald when he's back from leave.

In the meantime, it would be helpful to know your real-world use case for this so that we can consider it when considering any changes.

**Comment by Sagmedjo** [comment]
I am currently working on a multi page form with vue inertia. I've been searching for a method to omit the creation of several routes, which is the method most people use to implement a multi page form. 

Another option would be to create a counter which validates the form based on the page you are currently working on, but if you change the order of the pages or place a new one in between it is a big hassle to change.

To make the implementation of changes easier I developed a system, which generates a multi page form based on this array of objects: 
`formStructure: [
                    {
                        category: ""
                    },
                    {
                        message: ""
                    },
                    {
                        first_name: "",
                        last_name: "",
                        email: "",
                        phone: "",
                        company: "",
                        website: "",
                        subscribe_newsletter: 0,
                        privacy_policy: ""
                    },`

In order to switch to the next page I would like to validate the fields on the current page before allowing the user to move to the next one. 

I would want to use the "valid" or the "invalid" method to check if every field on the current page is valid. But

**Comment by Sagmedjo** [comment]
Sorry wrong button

**Comment by timacdonald** [comment]
Hi @Sagmedjo, when we tag the next version of Precognition, it will be possible to touch fields manually. This is useful when dealing with a multi-page form.

However, I don't believe we will add the ability to send an initial validation request across all inputs. This would make all required fields invalid before the user has entered any information.

Hopefully, with what is currently exposed and the new `touch` method, you will be able to achieve what you want.
