### ISSUE TITLE
Remember state on precognition form

### ISSUE THREAD

**Issue by KickSchutte67** [laravel/precognition#33]
Hello!

I am currently rewriting every useForm() instance to the precognition variant (``import { useForm } from 'laravel-precognition-vue-inertia';``). I want to "remember" the state of the form after submission, so the form is still "in tact" when going back to the form. 

I used to do this with: ``const form = useForm(`CreateQuote:${usePage().props.user.id}`, {``, but this does not work anymore. Does someone have a workaround to still accomplish this or is this not a feature (yet)? Thanks!

**Comment by jessarcher** [comment]
Hey @KickSchutte67,

We don't currently support passing a remember key to the underlying Inertia form, but I'll have a chat with @timacdonald about it and see what we can do.

**Comment by Bosphoramus** [comment]
I think this is pretty important, because it feels a little weird to lose functionality when using precognition

**Comment by timacdonald** [comment]
We can certainly support this. I supposed Precognition will have to remember some addition things also. Need to dig into the Inertia functionality to see how we can replicate it.

**Comment by timacdonald** [comment]
Hey folks, as this isn't specifically an issue - just a feature request we could (should) add, I'm going to close it.

It is on my list to add this feature and would be open to community PRs as well

**Comment by Danita** [comment]
Was this implemented? I'm using the latest version and the forms don't remember and I can't do something like `useRemember(useForm(...))` because it fails. Is there any workaround? Thanks!

**Comment by timacdonald** [comment]
It has not been implemented yet.

**Comment by Danita** [comment]
Thanks! @timacdonald Will it be implemented? Asking because this ticket is marked as closed and I don't see it tracked anywhere else. In case it will not, do you have any workaround we can apply?

**Comment by timacdonald** [comment]
I'd love to implement it but we don't have any concrete plans right now.

I'm not sure of any workarounds at the moment.

**Comment by valh1996** [comment]
> Was this implemented? I'm using the latest version and the forms don't remember and I can't do something like `useRemember(useForm(...))` because it fails. Is there any workaround? Thanks!

Did you find a easy workaround pls ?
