### ISSUE TITLE
Add support to force-validate specific fields (even if untouched)

### ISSUE THREAD

**Issue by xahmedtaha** [laravel/precognition#34]
Hi there !

I'm trying to implement a multi-step form (in the same page) and I'm using laravel-precognition-vue-inertia
I can't find a practical way to force validation for the fields contained in each step of the form even if they are untouched (in the handler of the "Next step" button for example) without affecting the whole form (fields in other steps) or submitting it .
How to achieve this behaviour?

**Comment by timacdonald** [comment]
@xahmedtaha we will be tagging this PR shortly, which will allow this behaviour: https://github.com/laravel/precognition/pull/26
