### ISSUE TITLE
form.submit with validate array does not work

### ISSUE THREAD

**Issue by cliff-paqt** [laravel/precognition#35]
### Laravel Precognition Plugin Version

0.3.1

### Laravel Version

10.0

### Plugin

Vue

### Description

I would like to add which fields on the form should be validated on submit. I would expect that populating the optional `validate` property with an array of paths would do this.
e.g.

`@change="form.validate('assets.0.address.zipcode' )"` 
works

but this doesn't:
```
const submit = () => {
    form.submit({
        validate: ['assets.0.address.zipcode', 'assets.0.address.number'],
    });
};

```

### Steps To Reproduce

add the code as mentioned in the description to your form
change the name(s) in the array of the`validate` property
See that it validates the whole form, instead of just the given names ('assets.0.address.zipcode', 'assets.0.address.number')

**Comment by timacdonald** [comment]
@cliff-paqt it is not possible to do this as a "submit" request is not a precognition request.

You would need to handle this on the back end yourself.

**Comment by makroxyz** [comment]
@cliff-paqt have you found any solution?

**Comment by cliff-paqt** [comment]
We went with the proposed soltution from timacdonald, but we set an object on the headers, specifying which part it should validate.

```
 formConfig = {
            headers: { part: validationPart },
        };
```
where you can add `formConfig` als a parameter on `form.submit`

The backend then uses a custom `shouldValidate` function to check which part it should validate.

**Comment by makroxyz** [comment]
> We went with the proposed soltution from timacdonald, but we set an object on the headers, specifying which part it should validate.
> 
> ```
>  formConfig = {
>             headers: { part: validationPart },
>         };
> ```
> 
> where you can add `formConfig` als a parameter on `form.submit`
> 
> The backend then uses a custom `shouldValidate` function to check which part it should validate.

Thank you, I almost undestand your solution. Could you kindly post a little example of validationPart and shouldValidate, please?

**Comment by cliff-paqt** [comment]
validationPart is just a string that is passed to the composable handling the eventual submit.

the shouldValidate on the backend should check if the headers exist for your error rule

**Comment by timacdonald** [comment]
Just a reminder that the framework does not do anything fancy with submissions, so there are security implications from limiting validation for plain submissions that are not handled and it is not recommended.

That being said, you are free to do whatever you need in your own applications 👍
