### ISSUE TITLE
Cannot find module /node_modules/laravel-precognition/dist/client'

### ISSUE THREAD

**Issue by thura-solinxtechnology** [laravel/precognition#36]
### Laravel Precognition Plugin Version

0.3.2

### Laravel Version

10.4.1

### Plugin

React

### Description

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 556 ms (18 modules)
- wait compiling...
- event compiled client and server successfully in 121 ms (18 modules)
- wait compiling /_error (client and server)...
- wait compiling /login (client and server)...
- event compiled client and server successfully in 3.6s (1272 modules)
- warn Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
- error Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/thuraaung/Works/solinx/next-testing/node_modules/laravel-precognition/dist/client' imported from /Users/thuraaung/Works/solinx/next-testing/node_modules/laravel-precognition/dist/index.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:231:11)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at ESMLoader.defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:323:32)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  digest: undefined
}
<img width="1074" alt="Screenshot 2023-07-15 at 12 25 57 PM" src="https://github.com/laravel/precognition/assets/124573470/216a55c4-667a-420e-99e5-8096dd77f4fd">

### Steps To Reproduce

Here i just done

- install fresh laravel with laravel new testing
- install fresh nextjs with mui
- install the package npm install laravel-precognition-react-inertia
- follow the guide for react https://laravel.com/docs/10.x/precognition#using-react
- run `npm run dev`

**Comment by jessarcher** [comment]
Sounds like the same issue as #30.

I've left a temporary solution in my reply at https://github.com/laravel/precognition/issues/30#issuecomment-1635107810 and we'll see if we can improve this.
