### ISSUE TITLE
Transform data before validation

### ISSUE THREAD

**Issue by elliotaldertonJump24** [laravel/precognition#38]
On our form we use the inertia form transform() method to transform some fields before posting (i.e. a datepicker field which return an object into a relevant string). Is there anyway we can transform a field before validating it?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by TheSnip3r** [comment]
I've a similar situation. I've a field that I used to do transformation to it before submission, but after using the package I cannot do that, since the reactivity and the submitted data for validation are coupled.
The backend expects specific structure and the frontend expects a different one.
I'm not sure how this can be resolved to be honest...

**Comment by timacdonald** [comment]
Hey folks, as a temporary solution, you could do the following:

```js
import { client, useForm } from 'laravel-precognition-vue'

client.axios().interceptors.request.use((request) => {
    request.data = {
        ...request.data,
        emails: request.data?.emails?.join(',')
    }

    return request
})

const form = useForm(/* ... */);

form.transform(/* ... */)
```

I've added this as an improvement we could make to the package and have the validator support the `transform` method without the need for this workout.

**Comment by joaopalopes24** [comment]
@timacdonald Has this functionality been removed?

**Comment by timacdonald** [comment]
Are you having an issue with something, @joaopalopes24?

**Comment by joaopalopes24** [comment]
I wanted to use the transform with `laravel-precognition-vue`, but I have this issue:

`Uncaught (in promise) TypeError: form.transform is not a function`

**Comment by timacdonald** [comment]
Which version of precognition do you have installed?

**Comment by joaopalopes24** [comment]
The latest version 0.7.1

**Comment by sebestenyb** [comment]
> Which version of precognition do you have installed?

Google brought me here, I am using `"laravel-precognition-vue": "^1.0.0"`, and same issue:

`Uncaught TypeError: useForm(...).transform is not a function`

<img width="654" height="269" alt="Image" src="https://github.com/user-attachments/assets/4b648d8b-4ac5-4681-a3dd-c732e033f38c" />

Also, searching for it in the codebase only yield a changelog result:

https://github.com/search?q=repo%3Alaravel%2Fprecognition%20transform&type=code

So I have the same question, was it removed, or it was never part of the `laravel-precognition-vue`?

It would be a super useful addition, lot of frontend components use their own data structure (👀  select boxes, check boxes, etc), transforming the data before sending to the backend would be lovely :)
