### ISSUE TITLE
laravel-precognition-vue-inertia didnt sent all data

### ISSUE THREAD

**Issue by rasyidialwee** [laravel/precognition#40]
### Laravel Precognition Plugin Version

0.4.1

### Laravel Version

10.18.0

### Plugin

Vue w/ Inertia

### Description

I am using laravel precognition to upload a photo and other data. I am using PUT method since I want to update it.

I tried to submit without the image, and i got the response just nice, 
When I tried to submit with files, i got errors on all the other fields.

here is my code 
```
const form = useForm(
  props.design ? 'put': "post",
  props.design ? route('designs.update', props.design.uuid):route("projects.designs.store", props.project.uuid),
  {
    images: [],
    type: props.design ? props.design.type:null,
    shortcode: props.design ? props.design.shortcode:null,
    price: props.design ? props.design.price:null,
  },
);
```

validation

```
 public function rules()
    {
        return [
            'images.*' => 'required|file|mimes:jpg,png',
            'type' => 'required|string',
            'shortcode' => 'required|alpha_dash|string|max:20|unique:designs,shortcode,' . $this->route('design')->id,
            'price' => 'required|numeric|min:1',
        ];
    }
```

### Steps To Reproduce

Create a form with file input and some other fields, and use PUT method.

**Comment by rasyidialwee** [comment]
NVM just notice that this behavior is expected, since we cant process file with method other than post

**Comment by valh1996** [comment]
Hi @timacdonald, just to be sure, the [inertia documentation](https://inertiajs.com/file-uploads#multipart-limitations) states:

> Uploading files using a multipart/form-data request is not natively supported in some server-side frameworks when using the PUT,PATCH, or DELETE HTTP methods. The simplest workaround for this limitation is to simply upload files using a POST request instead.
However, some frameworks, such as [Laravel](https://laravel.com/docs/11.x/routing#form-method-spoofing) and [Rails](https://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark), support form method spoofing, which allows you to upload the files using POST, but have the framework handle the request as a PUT or PATCH request. This is done by including a _method attribute in the data of your request.

Does the precognition package support spoofing the method, as does inertia? If yes, where do I send the spoofing method?
