### ISSUE TITLE
Laravel Precognition For Inertia Svelte

### ISSUE THREAD

**Issue by macellinoss275** [laravel/precognition#42]
Can we please get the Inertia Svelte version? Since Inertia could be implemented in React, Vue, and Svelte. I think it makes sense to have the Inertia Svelte version too.

**Comment by timacdonald** [comment]
@macellinoss275 we aren't currently planning a Svelte version, however it should be relatively straight foward to implement. You could probably build one out by looking at the drivers for the other frameworks.
