### ISSUE TITLE
Get a method for updating the URL in the form object

### ISSUE THREAD

**Issue by xphonse** [laravel/precognition#44]
For the `laravel-precognition-react`:

In Next.js, some values do not exist on the page first execution, like access to the localStorage, the window object, or the router query through the useRouter hook.

That means that setting a url for POST/PUT methods like `users/[id]`, where id is set by the url, is imposible, since it only exists after the first render and can be reached only by an useEffect hook

It would be nice to have a method to update the url in the useEffect, like `form.setUrl(url:string)`

**Comment by timacdonald** [comment]
Hey,

You may pass a function, instead of a string, to have the URL and method lazily evaluated.

```js
import { useForm } from 'laravel-precognition-react';
 
export default function Form() {
    const form = useForm(() => getFormMethod(), () => getFormUrl(), {
        name: '',
        email: '',
    });
 
    // ...
};
```

**Comment by xphonse** [comment]
The thing is that useForm initializes the url with the value that was there when useForm was called

I've worked with this example at user/[id].tsx but precognition doesn't set `id` at the end of the url, even if does get populated in the useEffect

```
  const [id, setId] = useState<string>('')

  useEffect(() => {
    if (!router.isReady) return
    setUuid(router.query.id as string)
  }, [router.isReady])

  const getPrecognitionUrl = (): string => 'http://b1.tenant.test/api/v6/admin-patroller/patroller/' + id

  const form = useForm('patch', () =>  getPrecognitionUrl(), {
    name: '',
    username: ''
  })
```

Thanks a lot for your time

**Comment by timacdonald** [comment]
@xphonse I this because we need to wrap the getPrecognitionUrl function in `useCallback` ?

https://react.dev/reference/react/useCallback

```js
const [id, setId] = useState<string>('')

useEffect(() => {
    if (router.isReady) {
        setUuid(router.query.id as string)
    }
}, [router.isReady])

const getPrecognitionUrl = useCallback((): string => 'http://b1.tenant.test/api/v6/admin-patroller/patroller/' + id, [id])

const form = useForm('patch', getPrecognitionUrl, {
    name: '',
    username: ''
})
```

If that doesn't work, I'm gonna need a reproduction repository to be able to dig in further and work out a solution for this one.

**Comment by xphonse** [comment]
I tried the useCallback approach but it still didn't work. I created a minimal example that reproduces the bug, instructions at the README: https://github.com/xphonse/Precognition-minimal

Again, thanks a lot for your time

**Comment by timacdonald** [comment]
@xphonse sorry for the delayed response here.

Just for your info, it seems that we needed a `ref` here instead - which works as expected...

```js
const [id, setId] = useState<string>('')
const url = useRef(null)

useEffect(() => {
  if (router.isReady) {
    setId(router.query.id as string)
    url.current = `https://example.com/api/users/${router.query.id}`
  }
}, [router.isReady])

const form = useForm('patch', () => url.current, {
    //
})
```
