### ISSUE TITLE
Possibility to override errors array

### ISSUE THREAD

**Issue by alainbelez** [laravel/precognition#45]
hello, is it possible to override the `onValidationError` method particularly the `setErrors(merge(omit({ ...errors }, validate), response.data.errors));` line, i am using laravel resources, and i am formatting the response to a different json format.

i tried to override the response on vue side using this code, it seems to work, but submitting the data doesn't have precognition header, and overriding all response would cause an issue.

Hoping for something like a getErrorKey method or something that set which `errors` key to use.

```
client.axios().interceptors.response.use(
  (response) => {
    return Promise.resolve(response);
  },
  (error) => {
    if (error.response.headers?.precognition === "true") {
      error.response.data = {
        message: error.response.data.meta.message,
        errors: error.response.data.meta.error_details,
      };
      return Promise.reject(error);
    }
    return Promise.reject(error);
  }
);

**Comment by timacdonald** [comment]
Hey there,

As we haven't had much demand for this yet, I don't want to introduce a first-party affordance when it is currently possible via Axios.

Try the following, which works for my application. You will want to do this in your `app.js` or `bootstrap.js` depending on your application setup.

```js
import { client } from 'laravel-precognition-{YOUR_PACKAGE_HERE}';

client.axios().interceptors.response.use(response => response, error => {

    // Transform your request here...
    error.response.data.errors = {
        name: ['The name is required.'],
    }

    return Promise.reject(error);
});

client.use(axios)
```
