### ISSUE TITLE
If the field is an array, also validate the items within the array

### ISSUE THREAD

**Issue by robtesch** [laravel/precognition#46]
Thanks for the great package. We are trying to add this to an existing project, and we are coming up a bit short when it comes to validated arrays of data (we are using Vue).

For example:

```vue
<script setup>
import { useForm } from 'laravel-precognition-vue';
 
const form = useForm('post', '/contact-groups', {
    name: '',
    emails: [],
});
 
const submit = () => form.submit();
</script>
 
<template>
    <form @submit.prevent="submit">
        <label for="name">Name</label>
        <input
            id="name"
            v-model="form.name"
            @change="form.validate('name')"
        />
        <div v-if="form.invalid('name')">
            {{ form.errors.name }}
        </div>
 
        <label for="emails">Contact Emails</label>
        <ArrayInput
            id="emails"
            v-model="form.emails"
            @change="form.validate('emails')"
        />
        <div v-if="form.invalid('emails')">
            {{ form.errors.emails }}
        </div>
 
        <button :disabled="form.processing">
            Create Contact Group
        </button>
    </form>
</template>
```

Then in the back end:

```php

protected function rules()
    {
        return [
            'name' => [
                'required',
                'min:3'
            ],
            'emails' => [
               'nullable',
               'array'
            ],
            'emails.*' => [
               'nullable',
               'email'
               'max:255',
            ],
        ];
    }

```

Given the following form data:

```json
{
  "name": "example",
  "emails": [
    "rttrhrht"
  ]
}
```

Precognition correctly validates the "emails" array, but it does not check that the items within the array are all emails and therefore shows the form as being completely valid. This is because of the `Precognition-Validate-Only` header with the value: `name,emails`. Would it be possible to detect if form.emails is an array, and if so, change the header to `name,emails,emails.*`?

If this change were to be made, we would also need to have some way of checking *which* items within the array were invalid. Laravel defaults to errors like this:

```json
{
  "message": "Please ensure you only have valid email addresses",
  "errors": {
    "emails.0": [
      "Please ensure you only have valid email addresses"
    ]
  }
}
```

We could either simply "reduce" these so that the whole "emails" field shows up as invalid, or we could allow the developer to try to find which keys are invalid with something like `form.invalidKeys('emails')`

**Comment by TheSnip3r** [comment]
+1
same issue

**Comment by timacdonald** [comment]
@robtesch this behaviour is intentional, as you might not have touched all items in the array, thus they should not be validated.

Here is a working example for what you are trying to achieve with a fresh Laravel Breeze installation. I've annotated the code for you.

```vue
<script setup>
import GuestLayout from '@/Layouts/GuestLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Link } from '@inertiajs/vue3';
import { useForm } from 'laravel-precognition-vue';

const form = useForm('post', '/register', {
    name: '',
    // I'd like to start with a single email input visible.
    // I could remove this if I didn't want any to start with.
    emails: [''],
});

const submit = () => {
    form.submit();
};
</script>

<template>
    <GuestLayout>
        <form @submit.prevent="submit">
            <div>
                <InputLabel for="name" value="Name" />

                <TextInput
                    id="name"
                    class="mt-1 block w-full"
                    v-model="form.name"
                    @change="form.validate('name')"
                />

                <InputError class="mt-2" :message="form.errors.name" />
            </div>

            <h2 class="font-bold mt-4">Email addresses</h2>

            <!--
                Show the validation errors attached to the `emails` rule.
            -->
            <InputError class="mt-1" :message="form.errors.emails" />

            <div v-for="(_, index) in form.emails" :key="index" class="mt-4">
                <!--
                    Using the index here to link the `for` to the input's `id` 
                -->
                <InputLabel :for="`email_${index}`" :value="`Email ${index + 1}`" />

                <!--
                    1. Using the index here to specify the email index to bind to.
                    2. Validating the specific email index that was changed.
                    This means the user will only see the error on the input
                    they actually interacted with.
                    3. Touch the root `emails` to ensure those rules are validated
                    and then validate the specific changed input.
                -->
                <TextInput
                    :id="`email_${index}`"
                    class="mt-1 block w-full"
                    v-model="form.emails[index]"
                    @change="form.touch('emails').validate(`emails.${index}`)"
                />

                <!--
                    Show the validation errors attached to the `emails.*` rule
                    for this particular input.
                -->
                <InputError class="mt-2" :message="form.errors[`emails.${index}`]" />
            </div>

            <!--
                Add a new email address to the list.
            -->
            <PrimaryButton type="button" @click="form.emails.push('')" class="mt-4">Add Email</PrimaryButton>

            <div class="flex items-center justify-end mt-4">
                <Link
                    :href="route('login')"
                    class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                    Already registered?
                </Link>

                <PrimaryButton class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Register
                </PrimaryButton>
            </div>
        </form>
    </GuestLayout>
</template>
```

Here is a quick video showing the form in practice. I added a `min:5` rule to the `emails` key to show that validation error.

https://github.com/laravel/precognition/assets/24803032/c12ad788-96d2-4f94-87a7-b7016b92894d


It is a little unfortunate that you have to manually `touch` the parent `email` key to see the validation errors for it. I opened a PR a while back that would remove this requirement. Thinking I might re-open it if we get some more feedback on this: https://github.com/laravel/precognition/pull/1

**Comment by robtesch** [comment]
Wow, thank you for the very detailed response. I didn't know about the "touch" method. I'm going to see if I can use the above to make my "Array Input" component work properly. For context, in my component, there is a single input field, which appends items to a list of "chips". The only way to edit these "chips" after they have been added is to remove them and re-add them. This is so that we can get a lot more items in the same amount of screen space. In an ideal world (and something I have working with my old implementation of validation), I would be able to highlight the invalid chips in red so that users could remove them. I think, given the approach you've shown above, I should be able to get this to work.

**Comment by mreduar** [comment]
> @robtesch this behaviour is intentional, as you might not have touched all items in the array, thus they should not be validated.
> It is a little unfortunate that you have to manually `touch` the parent `email` key to see the validation errors for it. I opened a PR a while back that would remove this requirement. Thinking I might re-open it if we get some more feedback on this: #1

Very good explanation, it helped me to understand what was happening, I was trying to understand it for a long time until I found this issue, I am having this problem too. on-change works fine, but not with touch. In this situation it would be ideal to validate all inputs for example: `form.touch(['title', 'fields.*']).validate();`
