### ISSUE TITLE
form.validating always false

### ISSUE THREAD

**Issue by makroxyz** [laravel/precognition#48]
### Laravel Precognition Plugin Version

0.5.1

### Laravel Version

10.22

### Plugin

Vue w/ Inertia

### Description

I can't see ```form.validating``` change while validating

### Steps To Reproduce

```vue
<input v-model="form.first_name" @change="form.validate('first_name')" />
 --- {{ form.validating }} ---
```

```js
const form = useForm('post', '/my-route', {
 first_name: null
})
```

**Comment by timacdonald** [comment]
Hey there,

I'm not able to reproduce this issue. If I create a fresh Laravel Breeze application:

```sh
composer create-project laravel/laravel preconition-test
cd preconition-test
composer install laravel/breeze
php artisan breeze:install vue
npm install laravel-precognition-vue
```

Then paste the following in the `Welcome.vue` file...

```vue
<script setup>
import { useForm } from 'laravel-precognition-vue';

const form = useForm('post', '/users', {
    name: '',
    email: '',
});

const submit = () => form.submit();
</script>

<template>
    <form @submit.prevent="submit">
        <label for="name">Name</label>
        <input
            id="name"
            v-model="form.name"
            @change="form.validate('name')"
        />
        <div v-if="form.invalid('name')">
            {{ form.errors.name }}
        </div>

        <label for="email">Email</label>
        <input
            id="email"
            type="email"
            v-model="form.email"
            @change="form.validate('email')"
        />
        <div v-if="form.invalid('email')">
            {{ form.errors.email }}
        </div>

        <div :class="form.validating ? 'font-bold text-green-500' : ''">
            Validating: {{ form.validating }}
        </div>

        <button :disabled="form.processing">
            Create User
        </button>
    </form>
</template>
```

Then build and serve the app...

```
npm run build
php artisan serve
```

I see the following. Note: I've added a 3 second sleep to my `public/index.php` file to make sure we see the change...


https://github.com/laravel/precognition/assets/24803032/b8273030-e45f-42c8-9a7e-93ec450c86b5

If this is still an issue, we made need a repository that reproduces the issue in isolation.

**Comment by makroxyz** [comment]
@timacdonald the issue is on laravel-precognition-vue-inertia

**Comment by timacdonald** [comment]
@makroxyz thanks for letting me know. Missed that sorry.

Fixed here: https://github.com/laravel/precognition/pull/49

Thanks for reporting this!
