### ISSUE TITLE
`laravel-precognition-vue-inertia` causes compilation errors with Inertia.js Vue 3 Composition API + TS

### ISSUE THREAD

**Issue by ibigforko** [laravel/precognition#5]
### Laravel Version

10.10

### PHP Version

8.2

### Database Driver & Version

MySQL Mac

### Description

I'm currently working on a Laravel project with Inertia.js Vue 3 Composition API and TypeScript. However, I've encountered an issue after installing and configuring laravel-precognition-vue-inertia. When I run my project, I see several errors in the terminal related to missing exports and modules in laravel-precognition. Here are the errors that I am seeing:

ERROR in ./node_modules/laravel-precognition-vue-inertia/dist/index.js 20:8-32
export 'toSimpleValidationErrors' (imported as 'toSimpleValidationErrors') was not found in 'laravel-precognition' (module has no exports)

ERROR in ./node_modules/laravel-precognition-vue/dist/index.js 29:22-37
export 'createValidator' (imported as 'createValidator') was not found in 'laravel-precognition' (module has no exports)

ERROR in ./node_modules/laravel-precognition-vue/dist/index.js 44:22-46
export 'toSimpleValidationErrors' (imported as 'toSimpleValidationErrors') was not found in 'laravel-precognition' (module has no exports)

ERROR in ./node_modules/laravel-precognition-vue/dist/index.js 91:19-30
export 'resolveName' (imported as 'resolveName') was not found in 'laravel-precognition' (module has no exports)

ERROR in ./node_modules/laravel-precognition-vue/dist/index.js 129:19-25
export 'client' (imported as 'client') was not found in 'laravel-precognition' (module has no exports)

ERROR in ./node_modules/laravel-precognition/dist/index.js 1:0-34
Module not found: Error: Can't resolve './client' in 'project-x/node_modules/laravel-precognition/dist'
Did you mean 'client.js'?
BREAKING CHANGE: The request './client' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json",".ts",".tsx",".vue"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json",".ts",".tsx",".vue"]'?

ERROR in ./node_modules/laravel-precognition/dist/index.js 2:0-85
Module not found: Error: Can't resolve './validator' in 'project-x/node_modules/laravel-precognition/dist'
Did you mean 'validator.js'?
BREAKING CHANGE: The request './validator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json",".ts",".tsx",".vue"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json",".ts",".tsx",".vue"]'?

ERROR in ./node_modules/laravel-precognition/dist/index.js 3:0-24
Module not found: Error: Can't resolve './types' in 'project-x/node_modules/laravel-precognition/dist'
Did you mean 'types.js'?
BREAKING CHANGE: The request './types' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json",".ts",".tsx",".vue"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json",".ts",".tsx",".vue"]'?`

**Comment by timacdonald** [comment]
Hey there,

Can you please create a minimal reproduction for this and we take a closer look?

```
laravel new bug-report --github="--public"
``` 

I was unable to reproduce this error on a fresh Laravel Breeze + Vue (composition API) + TypeScript project.

**Comment by MarekVikartovsky** [comment]
@ibigforko I ran into this issue today too, but I am using **laravel-precognition-vue** package. It seems it has something to do with webpack5. This error is mentioned in this [stackoverflow thread](https://stackoverflow.com/questions/70964723/webpack-5-in-ceate-react-app-cant-resolve-not-fully-specified-routes) and a solution is to put these settings to weback config and then it will work

```
{
    test: /\.m?js/,
    resolve: {
      fullySpecified: false,
    },
}
```

**Comment by joaopalopes24** [comment]
@ibigforko How did you resolved?

**Comment by cjholowatyj** [comment]
I'm currently having a similar issue with my project...

I'm using:

- `Laravel 10.25.1`
- `@inertiajs/vue3@1.0.12`
- `vue@3.3.6` (with `Composition API`, `<script setup> syntax`, `TypeScript`)
- `typescript@5.2.2`
- `PNPM` instead of `NPM`
- `laravel-precognition@0.3.2` (with `laravel-precognition-vue-inertia@0.3.2`)

I get the following error, but only when I try to run `php artisan inertia:start-ssr`:

```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/chrisholowatyj/Phpstorm/projects/keddy/node_modules/.pnpm/laravel-precognition@0.3.2/node_modules/laravel-precognition/dist/client' imported from /Users/chrisholowatyj/Phpstorm/projects/keddy/node_modules/.pnpm/laravel-precognition@0.3.2/node_modules/laravel-precognition/dist/index.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:226:11)
    at moduleResolve (node:internal/modules/esm/resolve:838:10)
    at defaultResolve (node:internal/modules/esm/resolve:1036:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.5.0
```

**Comment by joaopalopes24** [comment]
@cjholowatyj Try to update the package

**Comment by timacdonald** [comment]
I'm happy to look into this, but I'm unable to reproduce the issue. If someone can put together a reproduction repository I'm happy to help out.

@cjholowatyj How are you importing the `client`? If you have `laravel-precognition-vue-inertia` installed you should be importing it from there, e.g., 

```js
import {client} from 'laravel-precognition-vue-inertia';
```

I would also recommend updating to the latest version of Precognition, i.e., `^0.5.2`
