### ISSUE TITLE
form reset() w/o params doens't reset old values

### ISSUE THREAD

**Issue by makroxyz** [laravel/precognition#50]
### Laravel Precognition Plugin Version

0.5.2

### Laravel Version

10.29

### Plugin

Vue w/ Inertia

### Description

when call form.reset() without names parameters validator doesn't reset old values.

core/validator.js
```js
reset(...names) {
    if (names.length === 0) {
        setTouched([]) // <--- oldData is not reset
    } else {
        const newTouched = [...touched]

        names.forEach(name => {
            if (newTouched.includes(name)) {
                newTouched.splice(newTouched.indexOf(name), 1)
            }

            set(oldData, name, get(initialData, name))
        })

        setTouched(newTouched)
    }

    return form
```

next validation request doesn't start.

works if I reset with parameters

### Steps To Reproduce

```js
form.defaults({
  first_name: '',
  last_name: ''
}).reset()
```

form.touch('first_name', 'last_name')
form.validate() // <-- make request

form.reset()
form.touch('first_name', 'last_name')
form.validate() // <-- no request

form.reset('first_name', 'last_name')
form.touch('first_name', 'last_name')
form.validate() // <-- make request

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by makroxyz** [comment]
@driesvints could be a bug... what do I ask for in channels?

**Comment by driesvints** [comment]
Ask in a support channel if someone can confirm this bug.
