### ISSUE TITLE
async validate()

### ISSUE THREAD

**Issue by makroxyz** [laravel/precognition#51]
Is there a way to do this? 
In other words... wait for validation response

```js
function async nextStep() {
    await form.touch(["name", "email", "password", "password_validation"]).validate();

    return form.hasError
}
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by djurovicigoor** [comment]
I need the same thing. Did anoyne find a solution? @makroxyz

**Comment by makroxyz** [comment]
> I need the same thing. Did anoyne find a solution? @makroxyz

No, I also asked on Laracast forum... 

I hope @driesvints could have a look at this and also #50

**Comment by djurovicigoor** [comment]
I am using setTimeout() to wait for response right now but that is not a good approach

**Comment by makroxyz** [comment]
Same approach here, just a temporary workaround.. I'm using ’’’await promiseTimeout’’’ from vueuse/core library

**Comment by timacdonald** [comment]
We will be adding this feature. Follow along in https://github.com/laravel/precognition/issues/59

**Comment by timacdonald** [comment]
Opened for review: https://github.com/laravel/precognition/pull/69

**Comment by timacdonald** [comment]
Merged and tagged.

```vue
<TextInput
    v-model="form.name"
    @change="form.validate('name', {
        onSuccess: () => /* ... */,
        onValidationError: () => /* .. */,
    })"
/>
```

**Comment by makroxyz** [comment]
> Merged and tagged.
> 
> ```
> <TextInput
>     v-model="form.name"
>     @change="form.validate('name', {
>         onSuccess: () => /* ... */,
>         onValidationError: () => /* .. */,
>     })"
> />
> ```

Ok but I cannot understand how to wait for validation...

```js
function async nextStep() {
    await form.touch(["name", "email", "password", "password_validation"]).validate({
       ....
    });

    return form.hasError
}
```

**Comment by timacdonald** [comment]
Hopefully this makes more sense...

```
<button
    type="button"
    @click="form.touch(['name', 'email', 'phone']).validate({
        onSuccess: (response) => showNextStep(),
        onValidationError: (response) => focusFirstInvalidInput(),
    })"
>Next Step</button>
```

**Comment by makroxyz** [comment]
Sorry but I can't figure how to use it in my case

```vue
<b-button
    v-if="!stepper.isLast.value"
    :disabled="busy || validating"
    @click="next"
>
    Next
</b-button>
```

```js
const next = async () => {
    if (await validate()) {
        reset()
        goToNext()
    }
}

const validate = async () => {
    validating.value = true

    // isValid()  could be a form.validation or a simple boolean condition
    // form.validate doesn't wait for success or error...
    const valid = (await props.stepper.current.value?.isValid?.call()) ?? true

    if (valid) {
        reset()
    }

    emit('stepValidated', props.stepper.index.value, valid)

    validating.value = false

    validated(props.stepper.index.value, valid)

    return valid
}
```

**Comment by timacdonald** [comment]
I can't tell what all the custom code is doing here but I assume something like the following.

```html
<button
    type="button"
    v-if="!stepper.isLast.value"
    :disabled="busy || form.validating"
    @click="form.touch(['name', 'email', 'phone']).validate({
        onSuccess: (response) => {
            emit('stepValidated', props.stepper.index.value, true);

            reset();

            goToNext();
        },
    })"
>Next Step</button>
```

`onSuccess` is called when the validation call is successful. Do any work you need in there.
