### ISSUE TITLE
Bug: 422 (Unprocessable Content)

### ISSUE THREAD

**Issue by GustavoFenilli** [laravel/precognition#52]
### Laravel Precognition Plugin Version

0.5.2

### Laravel Version

10.10

### Plugin

Vue w/ Inertia

### Description

Every time input changes and blurs it gives this error: `POST http://127.0.0.1:8000/login 422 (Unprocessable Content)`, but the error correctly shows.

### Steps To Reproduce

1. `composer create-project laravel/laravel example-app`
2. `cd example-app`
3. `composer require laravel/breeze --dev`
4. `php artisan breeze:install`
5. `php artisan migrate`
6. `npm install laravel-precognition-vue-inertia`
7. Add middleware:
```php
Route::post('login', [AuthenticatedSessionController::class, 'store'])->middleware([HandlePrecognitiveRequests::class]);
```
9. Change the login page to use `useForm` from "laravel-precognition-vue-inertia":
```ts
const form = useForm("post", route("login"), {
    email: "",
    password: "",
    remember: false,
});

const submit = () => {
    form.submit({
        onFinish: () => {
            form.reset("password");
        },
    });
};
```
10. Add `@change="() => form.validate('email')"` to inputs:
```jsx
<TextInput
    id="email"
    type="email"
    class="mt-1 block w-full"
    v-model="form.email"
    @change="form.validate('email')"
    required
    autofocus
    autocomplete="username"
/>

<InputError class="mt-2" :message="form.errors.email" />

<TextInput
    id="password"
    type="password"
    class="mt-1 block w-full"
    v-model="form.password"
    @change="form.validate('password')"
    required
    autocomplete="current-password"
/>

<InputError class="mt-2" :message="form.errors.password" />
```
11. `mysqld --console`
12. `php artisan serve`
13. `npm run dev`
14. Go to the login page
15. Add any value to email or password and blur the input
16. Console Error!

**Comment by crynobone** [comment]
422 is the default HTTP status response for validation error:

https://github.com/laravel/framework/blob/20085feef61119b58fef540cba79595b4a85a89a/src/Illuminate/Validation/ValidationException.php#L25-L30

**Comment by GustavoFenilli** [comment]
Sure but should it be added to the console as an error?

**Comment by crynobone** [comment]
Can you provide some screenshot?

**Comment by GustavoFenilli** [comment]
Sure thing here is the setup:
![image](https://github.com/laravel/precognition/assets/14954720/d2345897-4f74-4222-b3ad-f2b9acdce96d)

And here is the page running after blur:
![image](https://github.com/laravel/precognition/assets/14954720/2ca05a82-f457-46c6-8e36-15d6ede86cad)

**Comment by crynobone** [comment]
The error came from the Browser, it's not something that we can override.

**Comment by GustavoFenilli** [comment]
So there is nothing wrong with my setup that gives an error in the console?

And if its a browser thing, in any case should this be looked upon as a production build shouldn't be giving a console error on every single blur/change.

**Comment by crynobone** [comment]
It's impossible to override Browser behavior.

**Comment by GustavoFenilli** [comment]
But just out of curiosity is there anything I can do to "fix" that error in the console or its just something I will have to "deal with it" when using Laravel Precognition as a validator?

**Comment by crynobone** [comment]
> is there anything I can do to "fix" that error in the console or its just something I will have to "deal with it" when using Laravel Precognition as a validator?

This error will also be shown on normal POST request with validation, and not only using Precognition.

**Comment by erip2** [comment]
I have the same problem as you, but for me the error is not shown at all. 

Maybe this is not the place to ask, but is your response an Inertia response?

Because I believe I have followed the documentation on how to set this up, but I can't seem to make it work.

I get a `422` response and the response I get is an object, not an Inertia response:

```js
{
  "message":
     "The date from field is required. (and 1 more error)",
     "errors":
        {
         "date_from":
             ["The date from field is required."],
         "date_to":
             ["The date to field is required."]
        }
}
```

causing the error not to be shown on the front-end.

> This error will also be shown on normal POST request with validation, and not only using Precognition.

I don't see this response on a normal Inertia response (when not using Precognition). I get a `302 Found` response.
