### ISSUE TITLE
Form reporting incorrectly valid

### ISSUE THREAD

**Issue by ahtinurme** [laravel/precognition#58]
### Laravel Precognition Plugin Version

0.5.2

### Laravel Version

10.35.0

### Plugin

Vue w/ Inertia

### Description

I checked this multiple times just to be sure, and here are the results:

1. When no validation is done - reporting correctly "invalid()" to be false and "valid()" to be false
<img width="365" alt="Screenshot 2023-12-13 at 14 45 53" src="https://github.com/laravel/precognition/assets/282119/7d6a172f-9175-4576-98e0-e853f8bd8169">

2. When validated with a correct value - reporting correctly "invalid()" to be false and "valid()" to be true
<img width="362" alt="Screenshot 2023-12-13 at 14 45 59" src="https://github.com/laravel/precognition/assets/282119/ebdaeb65-513e-40ab-87d4-87688847108b">

3. When validating with a not correct value - reporting "invalid()" to be true (correct) and "valid()" to be true (not correct):
<img width="368" alt="Screenshot 2023-12-13 at 14 46 06" src="https://github.com/laravel/precognition/assets/282119/f4643a48-445b-4c19-86fd-015b522ef251">

Expecting on 3rd example "invalid()" to be true and "valid()" to be false. It seems to me that currently the "valid()" acts as "isdirty" so the current name is misleading.

As a workaround, I use "!form.invalid(field) && form.valid(field)" to show the valid notification.

### Steps To Reproduce
```
<template>
invalid: {{ form.invalid('postalcode') }}<br>
valid: {{ form.valid('postalcode') }}<br>
<label for="postalcode">Postiindeks</label>
<input type="text" name="postalcode" v-model="form.postalcode" @change="form.validate('postalcode')">
</template>

<script setup>
import {useForm} from 'laravel-precognition-vue-inertia';

const form = useForm('post', 'valid-endpoint', {
  postalcode: null,
});
</script>
```

The validator:
```
<?php
namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SettingsRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'postalcode' => 'nullable|digits_between:10000,99999',
        ];
    }
```

**Comment by timacdonald** [comment]
Thanks for reporting. I've opened a PR for this. We can track the progress there: https://github.com/laravel/precognition/pull/60
