### ISSUE TITLE
laravel-precognition-vue-inertia `form.clearError('key')` clears all errors 

### ISSUE THREAD

**Issue by lazer-hybiz** [laravel/precognition#6]
### Laravel Version

10.12

### PHP Version

8.2

### Description

This is really an issue with the precognition package, but there is no repo to submit it 😕.

I added `laravel-precognition-vue-inertia` to my project, when manually calling `form.clearErrors('my-field')` all errrors are being cleared - unlike inertia's native`clearErrors` function where only `my-field` errors are being cleared

### Steps To Reproduce

Manually call `form.clearErrors('my-field')` on a form field where there are other field errors already set on the form.

**Comment by timacdonald** [comment]
I've opened #7 to address this issue. Thank you for reporting it.
