### ISSUE TITLE
Cannot use 'data' as a form property

### ISSUE THREAD

**Issue by adriaanzon** [laravel/precognition#61]
### Laravel Precognition Plugin Version

0.5.3

### Laravel Version

10.40.0

### Plugin

Vue

### Description

Because the properties of the form are merged together with form functions [here](https://github.com/laravel/precognition/blob/4c48ded938c30a2a0e29fad9757a5843314639e1/packages/vue/src/index.ts#L85), it's not possible to have a property on the form that has the same name as any of the functions.

### Steps To Reproduce

Example setup function of a Vue component, using a 'data' property:

```ts
const form = useForm('post', '/api/my-endpoint', {
    'data': {
        'foo': 1,
        'bar': 2,
    },
    'some_other_property': 1,
});

return { form };
```

When trying to submit the form using `form.submit()`, you'll get the following error because the 'data' property conflicts with the [data function](https://github.com/laravel/precognition/blob/4c48ded938c30a2a0e29fad9757a5843314639e1/packages/vue/src/index.ts#L86-L93):

```
TypeError: form.data is not a function. (In 'form.data()', 'form.data' is an instance of ProxyObject)
```

**Comment by driesvints** [comment]
This is indeed unfortunately a reserved keyword.
