### ISSUE TITLE
Live validation doesn't seem to work with Laravel 11

### ISSUE THREAD

**Issue by ludoguenet** [laravel/precognition#68]
### Laravel Precognition Plugin Version

0.5.4

### Laravel Version

11.1.1

### Plugin

Vue

### Description

After modifying my input, no error is returned live. In the Form object, the value of errors remains empty. However, it is filled with the correct error if I manually submit the form.

### Steps To Reproduce

Installing a classic version of Laravel 11 and Vue 3, as well as setting up the form identical to the documentation.

Adding simple email validation on the backend:

```php
$request->validate([
    'email' => [
        'required',
        'email',
    ],
]);
```

Observing that despite the `@change="form.validate('email')"` attribute, errors are not returned live.

**Comment by ludoguenet** [comment]
My bad. Validation didn't work because I wasn't using FormRequest.

**Comment by pindab0ter** [comment]
For those wondering, a `FormRequest` is required since an actual request is sent to the endpoint and the entire middleware stack is executed, but the controller function itself is not. The `FormRequest` moves the validation out of the non-executed controller function and into a place where it can be reached by the precognition request.

**Comment by chibyk101** [comment]
In my case, I installed the inertia package

`import { useForm } from "laravel-precognition-vue-inertia";`

`form.validate() ` does nothing.

the only method that does something when called is `form.submit()` so I only get validation on submission


```javascript <template>
    <v-form @submit.prevent="handleSubmit">
      <v-text-field
        v-model="form.job_title"
        :error-messages="form.errors.job_title"
        label="Job Title"
      ></v-text-field>
      <v-btn @click="form.validate()">Validate</v-btn>
      <v-btn type="submit">Submit</v-btn>
    </v-form>
  </template>
  
  <script setup>
  import { useForm } from "laravel-precognition-vue-inertia";
  
  const form = useForm("post", route("job-postings.store"), {
    job_title: "",
  });
  
  const handleSubmit = () => {
    form.submit();
  };
  </script>
```

```php
...
use App\Models\JobPosting;
use Illuminate\Foundation\Http\Middleware\HandlePrecognitiveRequests;

class JobPostingController extends Controller
{
    public function __construct()
    {
        $this->middleware(HandlePrecognitiveRequests::class)->only('store');
    }
 /**
     * Store a newly created resource in storage.
     */
    public function store(StoreJobPostingRequest $request)
    {
        $jobPosting = new JobPosting($request->validated());
        $jobPosting->save();

        return to_route('job-postings.show', $jobPosting)->with('success', 'Job Posted successfully');
    }
```

what can be wrong here? i can't find anything different from the docs

**Comment by timacdonald** [comment]
@chibyk101, I've answered your issue in the dedicated issue you opened: https://github.com/laravel/precognition/issues/89
