### ISSUE TITLE
Can we add PR for precognition with Support for React Native?

### ISSUE THREAD

**Issue by giunashvili** [laravel/precognition#76]

**Comment by driesvints** [comment]
We don't have any plans for this sorry.

**Comment by giunashvili** [comment]
@driesvints No I mean if I were to create PR for React Native support are you open to merging? or is it out of this repo's scope?

**Comment by driesvints** [comment]
No sorry, we don't want to take on the maintenance burden at this time. Thanks for offering though 👍
