### ISSUE TITLE
Trigger validation immediately if necessary

### ISSUE THREAD

**Issue by valh1996** [laravel/precognition#83]
Dear Laravel Team,

I need to trigger a function if I don't have errors in my form. But the function is triggered before validation takes place since I have the debounce function configured to avoid too many calls to the backend :

```ts
@onAdd="(current, updated, add) => {
  form.periods = updated
  form.validate('periods')
  if (form.valid('periods') {
    add()
  }
}" 
```

The proposal would be to have either a promise perhaps to be able to wait for the request to be carried out:
```ts
await form.validate('periods')
```

Otherwise to have either an `imediate` parameter on `form.validate()` to trigger validation directly/bypass the debounce time, e.g :
```ts
form.validate('periods', true)
``` 

Right now I suppose it's possible to watch `form.validating`, but it seems complicated.

What do you think?

**Comment by valh1996** [comment]
Ok just found #69, seems related

**Comment by timacdonald** [comment]
Can you please let me know what flavour of the plugin you are using?

I assume `vue` or `vue-inertia`?

**Comment by valh1996** [comment]
I use `vue-inertia` (but don't I need the `vue`plugin also installed to use the `vue-inertia` one?)

**Comment by timacdonald** [comment]
Nah, just `vue-inertia` is good.

Until we merge the async validate feature, which would make this nicer for you, you could do the following...

```js
const form = useForm(/* ... */);

form.validator().on('errorsChanged', () => {
    if (form.valid('periods') {
        add()
    }
})
```

Hope that helps.

**Comment by timacdonald** [comment]
Opened for review: https://github.com/laravel/precognition/pull/69

**Comment by timacdonald** [comment]
Merged and tagged.

```vue
<TextInput
    v-model="form.name"
    @change="form.validate('name', {
        onSuccess: () => /* ... */,
        onValidationError: () => /* .. */,
    })"
/>
```

**Comment by valh1996** [comment]
> Merged and tagged.
> 
> ```
> <TextInput
>     v-model="form.name"
>     @change="form.validate('name', {
>         onSuccess: () => /* ... */,
>         onValidationError: () => /* .. */,
>     })"
> />
> ```

@timacdonald Is there such a thing as `onFinish`, which would avoid having to execute the same code on both `onValidationError` and `onSuccess` ?

**Comment by timacdonald** [comment]
There is.

```html
<TextInput
    v-model="form.name"
    @change="form.validate('name', {
        onFinish: () => /* ... */,
    })"
/>
```

**Comment by timacdonald** [comment]
It has been tagged.
