### ISSUE TITLE
Precognition is not working for the specified route

### ISSUE THREAD

**Issue by siarheipashkevich** [laravel/precognition#87]
### Laravel Precognition Plugin Version

0.5.6

### Laravel Version

11.19.0

### Plugin

React

### Description

I'm trying to play with your package and want to decide to use it or not.

But I'm facing with some not obvious issues which not documented:
1) we must add `precognition` header to `exposed_headers` property in `cors.php` file
2) I want to specify `HandlePrecognitiveRequests` middleware to the specific route of my controller (store method):
<img width="667" alt="image" src="https://github.com/user-attachments/assets/1ac44030-de63-4d7f-809a-39c6f9330523">

But it's not workin and I'm getting an error on the front-end side:
<img width="1909" alt="image" src="https://github.com/user-attachments/assets/caced6cf-b20d-4b2f-9c9f-7faf44776c38">

What am I doing wrong?

### Steps To Reproduce

Please see description above.

Thanks

**Comment by driesvints** [comment]
We'd welcome a PR to the docs for the firs issue. For the second one I kindly redirect you to a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by siarheipashkevich** [comment]
@timacdonald could you please take a look at the second issue?

I think there is really problem, I also try to add `options` route but nothing.

**Comment by timacdonald** [comment]
@siarheipashkevich, I'm unable to reproduce the issue you are hitting with a fresh Laravel application. Could you provide a minimal reproduction repository?

**Comment by siarheipashkevich** [comment]
@timacdonald sorry, it's my fault. Take a look at my `only` parameter which is wrong.. I should declare `store` not `post` ((

**Comment by timacdonald** [comment]
ahhh! Gotcha. Easily done.

Dop you think the CORS issue is still a problem or was it just the `only` parameter that was the issue?

**Comment by siarheipashkevich** [comment]
I think it's still an issue. Because it's not obvious right now.
Yes, we have mention about Precognition header in the documentation, but nothing about Precognition-Success etc

And I think will be better to notice about this if the Laravel used as API.

Thanks for your answers and attemptings to make Laravel packages better!
