### ISSUE TITLE
form.setTouched is not a function vue

### ISSUE THREAD

**Issue by msirse** [laravel/precognition#93]
### Laravel Precognition Plugin Version

0.5.8

### Laravel Version

11.0.0

### Plugin

Vue

### Description

setTouched is not a function in vue plugin.

### Steps To Reproduce

 form.setTouched(["first_name"]).validate({
        onSuccess: (response) => {
            nextStep();
        },
    });
    
    setTouched is not a function in vue plugin.

**Comment by timacdonald** [comment]
You will want to use `form.touch`. I mistyped `setTouched` in some of the issues in the repo. I've just gone and corrected that.

```
<button
    type="button"
    @click="form.touch(['name', 'email', 'phone']).validate({
        onSuccess: (response) => nextStep(),
        onValidationError: (response) => /* ... */,
    })"
>Next Step</button>
```
