### ISSUE TITLE
Multi step wizard

### ISSUE THREAD

**Issue by msirse** [laravel/precognition#95]
### Laravel Precognition Plugin Version

0.5.8

### Laravel Version

11

### Plugin

Vue w/ Inertia

### Description

Multi step wizard and user validate first step and jump to second step. Then click back and jump back to first step.

If the user has not touched any fields, you cannot validate the same fileds. How can I now than form is alrady validated and skip validation, and jump to second step.

### Steps To Reproduce

Step 1

skip validation if the user has not touched any fields and the form has already been validated or validate again....

form.touch(["first_name", "last_name"]).validate({
        onSuccess: (response) => {
           nextStep()
        },
 });

**Comment by timacdonald** [comment]
We would need to add a `setTouched` function to allow you to control what fields are currently touched. The `touch` function is always additive.

```js
form.touch(['name'])

form.touch(['email'])

// name and email are now "touched"
```

**Comment by e4se** [comment]
For now, this can be resolved using the following approach before the touch method
`form.validator().reset()`

**Comment by mreduar** [comment]
> For now, this can be resolved using the following approach before the touch method `form.validator().reset()`

This did not work for me, calling the reset method seems to work the same and the validation is not given. Could you explain a little better how you made it work? I currently have a bug and this is stopping me.

**Comment by e4se** [comment]
I forgot about `onBeforeValidation` hook. Like This:
`form.validator().reset();
 form.touch([
      'name',
      'description',
  ]).validate({
      onBeforeValidation: (newRequest) => {
          return true
      },
      onSuccess: () => {
      },
  });
`

**Comment by mreduar** [comment]
> I forgot about `onBeforeValidation` hook. Like This:
> 
> ```
> form.validator().reset();
> form.touch([
>     'name',
>     'description',
> ]).validate({
>     onBeforeValidation: (newRequest) => {
>         return true
>     },
>     onSuccess: () => {
>     },
> });
> ```

Thank you so much @e4se ! Works great

**Comment by timacdonald** [comment]
PR up for this one: https://github.com/laravel/precognition/pull/105

**Comment by timacdonald** [comment]
See [my other comment](https://github.com/laravel/precognition/issues/99#issuecomment-2461420562) on some more improvements to handling wizards. Removes the need for the `touch` call and allows for navigating forward and backward in the wizard without the pages conflicting with each other.
