### ISSUE TITLE
`setError` doesn't work as expected, returns `key` instead of the key provided

### ISSUE THREAD

**Issue by erip2** [laravel/precognition#96]
### Laravel Precognition Plugin Version

0.5.8

### Laravel Version

11.0

### Plugin

Vue w/ Inertia

### Description

The `form.setError` doesn't work as it does with the Inertia `useForm` helper.

I want to do a quick front-end validation before I send the data on the server, in cases where the user can't add some data if some other data is empty.

I noticed that when using the `laravel-precognition-vue-inertia'` the errors aren't shown, and that's because the form errors object is like this:

```
errors:
  key: "Shipping Cost is required."
```

from the Vue Developer tools. Normally should be `{ 'shipping_cost': "Shipping Cost is required" }` as the function is called like this: `form.setError('shipping_cost', 'Shipping Cost is required')`.

I debugged it and noticed that for some reason, the object is returned with `key` instead of the input name:

<img width="683" alt="Screenshot 2024-09-09 at 15 23 56" src="https://github.com/user-attachments/assets/1260cad0-d950-401c-91a7-1da043c9f307">

### Steps To Reproduce

- Create an Inertia/Laravel project
- Use the `laravel-precognition-vue-inertia` `useForm`
- Try to set an error manually with `setError` function

**Comment by timacdonald** [comment]
PR up to fix this one. Will close this and we can follow along in that PR: https://github.com/laravel/precognition/pull/97

**Comment by timacdonald** [comment]
Thanks for reporting this one.
